SUCCESS_CODE = 0

ERROR_AUTH_USERNAME_EXISTS = 100
ERROR_AUTH_USERNAME_UNALLOWED_CHARACTERS = 101
ERROR_AUTH_USERNAME_LENGTH = 102
ERROR_AUTH_USERNAME_CONFLICTS = 103
ERROR_AUTH_PASSWORD_LENGTH = 104
ERROR_AUTH_PASSWORD_DO_NOT_MATCH = 105
ERROR_AUTH_TITLE_LENGTH = 106
ERROR_AUTH_TITLE_EMPTY = 107
ERROR_AUTH_USERNAME_UNKNOWN = 108
ERROR_AUTH_PASSWORD_WRONG = 109

ERROR_USER_NOT_FOUND = 200

ERROR_POST_EMPTY = 300
ERROR_POST_NOT_FOUND = 301
ERROR_POST_ACCESS_DENIED = 302